[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "产品"
url = "/products/"
identifier = "products"
weight = 10

  [[main]]
  name = "Plastic Pallet"
  url = "/products/pallet/"
  parent = "products"
  weight = 11

  [[main]]
  name = "Nestable Blow-Mold Pallets"
  url = "/products/blow-mold/"
  parent = "products"
  weight = 12

  [[main]]
  name = "Plastic Crates & Boxes"
  url = "/products/crate-box/"
  parent = "products"
  weight = 13

  
  [[main]]
  name = "Foldable Pallet Boxes"
  url = "/products/fold/"
  parent = "products"
  weight = 14

  [[main]]
  name = "Large Bulk Containers"
  url = "/products/l-container/"
  parent = "products"
  weight = 15

  [[main]]
  name = "Plastic Waste Bins"
  url = "/products/waste/"
  identifier = "products-dimension"
  parent = "products"
  weight = 16

[[main]]
name = "Industries"
url = "/industries/"
identifier = "industries"
weight = 20

  [[main]]
  name = "Cold Chain Logistics Solutions"
  url = "/industries/cold-chain/"
  parent = "industries"
  weight = 21

  [[main]]
  name = "High-Bay Racking Storage Solutions"
  url = "/industries/warehousing/"
  parent = "industries"
  weight = 22

  [[main]]
  name = "Export One-Way Pallets"
  url = "/industries/export/"
  parent = "industries"
  weight = 23

  [[main]]
  name = "Food-Grade Pallet Applications"
  url = "/industries/food-grade/"
  parent = "industries"
  weight = 24

  [[main]]
  name = "Chemical & Hazardous Goods Storage"
  url = "/industries/chemical/"
  parent = "industries"
  weight = 25

[[main]]
name = "Resources"
url = "/resources/"
identifier = "resources"
weight = 30

  [[main]]
  name = "articles"
  url = "/resources/articles/"
  parent = "resources"
  weight = 31

  [[main]]
  name = "News"
  url = "/resources/news/"
  parent = "resources"
  weight = 32

  [[main]]
  name = "Downloads"
  url = "/resources/downloads/"
  parent = "resources"
  weight = 33

  [[main]]
  name = "FAQ"
  url = "/resources/faq/"
  parent = "resources"
  weight = 34

[[main]]
name = "About Us"
url = "/about/"
identifier = "about"
weight = 40

[[main]]
name = "Contact Us"
url = "/contact/"
identifier = "contact"
weight = 50
