[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "产品"
url = "#"
identifier = "products"
weight = 10

  [[main]]
  name = "塑料托盘"
  url = "/products/pallet/"
  parent = "products"
  weight = 11

  [[main]]
  name = "吹塑可嵌套塑料托盘"
  url = "/products/blow-mold/"
  parent = "products"
  weight = 12

  [[main]]
  name = "板条箱"
  url = "/products/crate-box/"
  parent = "products"
  weight = 13

  
  [[main]]
  name = "可折叠塑料托盘箱"
  url = "/products/fold/"
  parent = "products"
  weight = 14

  [[main]]
  name = "大型散装容器"
  url = "/products/l-container/"
  parent = "products"
  weight = 15

  [[main]]
  name = "塑料垃圾桶"
  url = "/products/waste/"
  identifier = "products-dimension"
  parent = "products"
  weight = 16

[[main]]
name = "行业案例"
url = "#"
identifier = "industries"
weight = 20

  [[main]]
  name = "仓储物流"
  url = "/industries/warehousing-logistics/"
  parent = "industries"
  weight = 21

  [[main]]
  name = "冷链生鲜"
  url = "/industries/cold-chain-fresh/"
  parent = "industries"
  weight = 22

  [[main]]
  name = "高位货架"
  url = "/industries/high-bay-racking/"
  parent = "industries"
  weight = 23

  [[main]]
  name = "食品饮料"
  url = "/industries/food-beverage/"
  parent = "industries"
  weight = 24

  [[main]]
  name = "农业"
  url = "/industries/agriculture/"
  parent = "industries"
  weight = 25

  [[main]]
  name = "制造与零部件"
  url = "/industries/manufacturing-parts/"
  parent = "industries"
  weight = 26

  [[main]]
  name = "化工原料"
  url = "/industries/chemical-materials/"
  parent = "industries"
  weight = 27


[[main]]
name = "资源中心"
url = "#"
identifier = "resources"
weight = 30

  [[main]]
  name = "博客"
  url = "/resources/articles/"
  parent = "resources"
  weight = 31

  [[main]]
  name = "新闻动态"
  url = "/resources/news/"
  parent = "resources"
  weight = 32

  [[main]]
  name = "下载中心"
  url = "/resources/downloads/"
  parent = "resources"
  weight = 33

  [[main]]
  name = "常见问题"
  url = "/resources/faq/"
  parent = "resources"
  weight = 34

[[main]]
name = "关于我们"
url = "/about/"
identifier = "about"
weight = 40

[[main]]
name = "联系我们"
url = "/contact/"
identifier = "contact"
weight = 50

