[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Products"
url = "#"
identifier = "products"
weight = 10

  [[main]]
  name = "Plastic Pallet"
  url = "/products/pallet/"
  parent = "products"
  weight = 11

  [[main]]
  name = "Nestable Blow-Mold Pallets"
  url = "/products/blow-mold/"
  parent = "products"
  weight = 12

  [[main]]
  name = "Plastic Crates & Boxes"
  url = "/products/crate-box/"
  parent = "products"
  weight = 13

  
  [[main]]
  name = "Foldable Pallet Boxes"
  url = "/products/fold/"
  parent = "products"
  weight = 14

  [[main]]
  name = "Large Bulk Containers"
  url = "/products/l-container/"
  parent = "products"
  weight = 15

  [[main]]
  name = "Plastic Waste Bins"
  url = "/products/waste/"
  identifier = "products-dimension"
  parent = "products"
  weight = 16

[[main]]
name = "Industries"
url = "#"
identifier = "industries"
weight = 20

  [[main]]
  name = "Warehousing"
  url = "/industries/warehousing-logistics/"
  parent = "industries"
  weight = 21

  [[main]]
  name = "Cold Chain"
  url = "/industries/cold-chain-fresh/"
  parent = "industries"
  weight = 22

  [[main]]
  name = "High Rack"
  url = "/industries/high-bay-racking/"
  parent = "industries"
  weight = 23

  [[main]]
  name = "Food & Beverage"
  url = "/industries/food-beverage/"
  parent = "industries"
  weight = 24

  [[main]]
  name = "Agriculture"
  url = "/industries/agriculture/"
  parent = "industries"
  weight = 25

  [[main]]
  name = "Manufacturing"
  url = "/industries/manufacturing-parts/"
  parent = "industries"
  weight = 26

  [[main]]
  name = "Chemicals"
  url = "/industries/chemical-materials/"
  parent = "industries"
  weight = 27


[[main]]
name = "Resources"
url = "#"
identifier = "resources"
weight = 30

  [[main]]
  name = "articles"
  url = "/resources/articles/"
  parent = "resources"
  weight = 31

  [[main]]
  name = "News"
  url = "/resources/news/"
  parent = "resources"
  weight = 32

  [[main]]
  name = "Downloads"
  url = "/resources/downloads/"
  parent = "resources"
  weight = 33

  [[main]]
  name = "FAQ"
  url = "/resources/faq/"
  parent = "resources"
  weight = 34

[[main]]
name = "About Us"
url = "/about/"
identifier = "about"
weight = 40

[[main]]
name = "Contact Us"
url = "/contact/"
identifier = "contact"
weight = 50
